[2025-10-23T17:03:13.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_dop_operator_v3.should_run scheduled__2025-10-23T17:02:00+00:00 [queued]>
[2025-10-23T17:03:13.513+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_dop_operator_v3.should_run scheduled__2025-10-23T17:02:00+00:00 [queued]>
[2025-10-23T17:03:13.513+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-23T17:03:13.517+0000] {taskinstance.py:1382} INFO - Executing <Task(_BranchPythonDecoratedOperator): should_run> on 2025-10-23 17:02:00+00:00
[2025-10-23T17:03:13.520+0000] {standard_task_runner.py:57} INFO - Started process 626 to run task
[2025-10-23T17:03:13.522+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'example_branch_dop_operator_v3', 'should_run', 'scheduled__2025-10-23T17:02:00+00:00', '--job-id', '17', '--raw', '--subdir', '/home/airflow/.local/lib/python3.11/site-packages/airflow/example_dags/example_branch_python_dop_operator_3.py', '--cfg-path', '/tmp/tmpwz851wza']
[2025-10-23T17:03:13.523+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask should_run
[2025-10-23T17:03:13.557+0000] {task_command.py:416} INFO - Running <TaskInstance: example_branch_dop_operator_v3.should_run scheduled__2025-10-23T17:02:00+00:00 [running]> on host eb62ebeb0a5d
[2025-10-23T17:03:13.595+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='example_branch_dop_operator_v3' AIRFLOW_CTX_TASK_ID='should_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T17:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-23T17:02:00+00:00'
[2025-10-23T17:03:13.598+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-10-23T17:03:13.598+0000] {logging_mixin.py:154} INFO - ------------- exec dttm = 2025-10-23T17:02:00+00:00 and minute = 2
[2025-10-23T17:03:13.598+0000] {python.py:194} INFO - Done. Returned value was: empty_task_1
[2025-10-23T17:03:13.598+0000] {python.py:227} INFO - Branch callable return empty_task_1
[2025-10-23T17:03:13.598+0000] {skipmixin.py:173} INFO - Following branch empty_task_1
[2025-10-23T17:03:13.608+0000] {skipmixin.py:239} INFO - Skipping tasks [('empty_task_2', -1)]
[2025-10-23T17:03:13.629+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_branch_dop_operator_v3, task_id=should_run, execution_date=20251023T170200, start_date=20251023T170313, end_date=20251023T170313
[2025-10-23T17:03:13.666+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-23T17:03:13.679+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
